name: NodeJS with Gulp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Use Node.js 18
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install Dependenc
        run: npm ci
      - name: Build Prod  
        run: gulp --production
      - name: Upload Artifact
        with: 
          path: build
          name: build-files
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build priject
        uses: actions/download-artifact@v3
        with: 
          name: build-files
      
